/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.majsky.zapeky;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import org.apache.commons.io.IOUtils;

import javax.swing.*;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.charset.StandardCharsets;

public class App {

    public static final String BASE_URL = "https://raw.githubusercontent.com/majsky/zapekaren_update/master/pack/";

    private static Gson gson;

    public static void main(String[] args) throws IOException {
        gson = new GsonBuilder().setPrettyPrinting().create();

        try {
            IOUtils.toString(url("info.json"), StandardCharsets.UTF_8);
        }catch (IOException e){
            showError("Nepodarilo sa skontrolovat aktualizacie\n(nejde internet?)");
            return;
        }
    }

    private static URL url(String end){
        try {
            return new URL(BASE_URL + end);
        } catch (MalformedURLException e) {
            e.printStackTrace();
            showError(e.getLocalizedMessage());
            System.exit(1);
            return null;
        }
    }

    private static void showError(String s){
        JOptionPane.showMessageDialog(null, s, "ZapekarenUpdate", JOptionPane.ERROR_MESSAGE);
    }
}
